returntocorp/sgrep

sgrep.py

Exits 0 if all yaml files are valid or non-zero if not valid

add --validate flag

---

sgrep.py

Need to this to unblock https://github.com/returntocorp/echelon-backend/issues/3948. And fixes https://github.com/returntocorp/sgrep/issues/16
To test:
```json
ulziibayarotgonbaatar@ulziibayars-MacBook-Pro sgrep % sgrep-lint --r2c ~/Workspace/sgrep-rules/python/flask/ ~/Workspace/sgrep-rules/tests/python/flask/app_run_security_config/ | jq
running 17 rules from 4 yaml files (0 yaml files were invalid)
{
"results": [
{
"check_id": "/.Users.ulziibayarotgonbaatar.Workspace.sgrep-rules.python.flask.avoid_using_app_run_directly",
"path": "/Users/ulziibayarotgonbaatar/Workspace/sgrep-rules/tests/python/flask/app_run_security_config/test_avoid_using_app_run_directly.py",
"start": {
"line": 1,
"col": 1
},
"end": {
"line": 1,
"col": 8
},
"extra": {
"message": "app.run(...) is ignored by flask. …
```

Add --r2c to indicate platform compatible output format

---

sgrep.py

Fixing what appears to be a typo

Fixed minor typo

---

.circleci/config.yml

add mac build on merge to master (#46)

---

sgrep.py

Sorry my vscode formatter munched some things @DrewDennison

add option to skip rewriting rule ids (useful for tests)

---

bin/main_sgrep.ml

This fixes issue #6
Test plan:
echo '$X == $X' | ./_build/default/bin/main_sgrep.exe -lang python --validate-pattern-stdin
pad@yrax:~/github/sgrep$ echo $?
0
pad@yrax:~/github/sgrep$ echo '$X == ' | ./_build/default/bin/main_sgrep.exe -lang python --validate-pattern-stdin
pad@yrax:~/github/sgrep$ echo $?
1

New --validate-pattern-stdin command for sgrep, to be used in CI

---

lib/generic_vs_generic.ml

removal of Nop and additions of a few more expr option
test plan: make test still works

* lib/generic_vs_generic.ml: CEs on recent changes on ast_generic

---

tests/java/misc_assert.java
tests/java/misc_assert.sgrep

* tests/java/misc_assert.java: regression test

---

lib/generic_vs_generic.ml

php_to_generic.ml introduced a few new constructs in ast_generic.ml

* lib/generic_vs_generic.ml: adapt to changes in ast_generic.ml after

---

tests/js/dots_params.js
tests/js/dots_params.sgrep

Also this should show issue #178 is now fixed

* tests/js/dots_params.js: support!

---

sgrep.py
testlint/test_lint.py

As now SgreRange instead of Range is used a couple of places.

Prototype where-python pattern, need to fix other test cases

---

tests/js/misc_id_vs_name.js
tests/js/misc_id_vs_name.sgrep

Test plan: with latest pfff, make test now work.
This show that issue #195 is fixed.

Test files for issue #195

---

.circleci/config.yml
Makefile
sgrep_lint/Makefile

Moved to separate makefile, cc @aryx

build sgrep lint separately

---

README.md
sgrep/tests/generate_test_matrix.py

<table style="text-align:center">
<tr>
<td>
</td>
<td>
<b>go</b>
</td>
<td>
<b>python</b>
</td>
<td>
<b>js</b>
</td>
<td>
<b>java</b>
</td>
<td>
<b>php</b>
</td>
<td>
<b>ml</b>
</td>
<td>
<b>cpp</b>
</td>
<td>
<b>c</b>
</td>
</tr>
<tr>
<td>
'...' operator
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🔶
</td>
</tr>
<tr>
<td>
Equivalences
</td>
<td>
🔶
</td>
<td>
🔶
</td>
<td>
🔶
</td>
<td>
🔶
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🔶
</td>
</tr>
<tr>
<td>
Metavariables
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
✅
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
✅
</td>
</tr>
<tr>
<td>
Others
</td>
<td>
🔶
</td>
<td>
✅
</td>
<td>
🔶
</td>
<td>
🔶
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🚧
</td>
<td>
🚧
</td>
</tr>
<tr>
<td> …

Improve README with feature matrix

---

sgrep/lib/generic_vs_generic.ml
sgrep/lib/generic_vs_generic.mli
sgrep/lib/sgrep_generic.ml
sgrep/lib/subast_generic.ml
sgrep/lib/subast_generic.mli
sgrep/tests/js/deep_stmt.js
sgrep/tests/js/deep_stmt.sgrep
sgrep/tests/js/deep_stmt2.js
sgrep/tests/js/deep_stmt2.sgrep
sgrep/tests/python/deep_fake_dataflow.py
sgrep/tests/python/deep_fake_dataflow.sgrep

This should fix issue #229.
It's very hacky but it works, and does not seem too slow.
Test plan:
Test files included

Deep stmt matching!

---

sgrep/tests/js/equivalence_import_variations.js
sgrep/tests/js/equivalence_import_variations.sgrep
sgrep/tests/js/imports.TODO

This fixes issue #250
Test plan:
test files included
cd sgrep; make test

Test files showing support for import declaration pattern in sgrep.

---

sgrep/lib/generic_vs_generic.ml
sgrep/tests/go/dots_stmts.go
sgrep/tests/go/misc_hidden_empty.go
sgrep/tests/go/misc_hidden_empty.sgrep
sgrep/tests/go/misc_hidden_empty2.go
sgrep/tests/go/misc_hidden_empty2.sgrep

This fixes issue #281
Test plan:
test file included

Test files showing you can now use multiple stmts patterns in Go

---

sgrep/lib/generic_vs_generic.ml

Remove useless return ()

---

Dockerfile
sgrep/bin/dune
sgrep/sgrep.opam
sgrep/tests/dune

Pfff requires now dypgen and menhir

Update to latest pfff

---

.github/workflows/release.yml
sgrep_lint/build.sh
sgrep_lint/sgrep-lint

Use tar to preserve file permissions in artifact
Use python3.7 when calling nuitka

Fix builds to work on fresh Ubuntu 18.04 instance

---

sgrep/bin/main_sgrep.ml

Description: I was calling Naming_ast.resolve only when
calling sgrep with -e, and not via -rules_file.
This is quick fix. The right fix is to factorize more code
between sgrep_generic and sgrep_lint_generic to stop having
slightly different behaviors between -e and -rules_file.
Test plan:
pad@yrax:~/github/sgrep/sgrep$ cat /tmp/file.yaml
rules:
- id: test-constants
pattern: foo("...")
message: "foo!"
languages: [js]
severity: ERROR
pad@yrax:~/github/sgrep/sgrep$ yy -lang js -rules_file /tmp/file.yaml /tmp/equivalence_constant_propagation3.js
+ /home/pad/github/sgrep/sgrep/_build/default/bin/main_sgrep.exe -lang js -lang js -rules_file /tmp/file.yaml /tmp/equivalence_constant_propagation3.js
{
"matches": [
{
"check_id": "test-constants",
"path": …

Call Naming_ast.resolve for constant propagation in every mode

---

sgrep/lib/generic_vs_generic.ml
sgrep/tests/python/aliasing_attribute.py
sgrep/tests/python/aliasing_attribute.sgrep

This fixes issue #294
Test plan:
test files included

Resolving alias in attributes/decorators

---

sgrep_lint/sgrep.py

Closes https://github.com/returntocorp/sgrep/issues/317

Add version string and command to print it out

---

sgrep/tests/js/misc_destructuring.js
sgrep/tests/js/misc_destructuring.sgrep
sgrep/tests/js/unordered_destructuring.js
sgrep/tests/js/unordered_destructuring.sgrep

this fixes issue #337
Test plan:
test file included

Use latest pfff so destructuring assignments are not transpiled and work

---

sgrep/lib/generic_vs_generic.ml
sgrep/tests/python/metavar_kwd_arg.py
sgrep/tests/python/metavar_kwd_arg.sgrep

This fixes issue #367
Test plan:
test file included

Support for metavar on keyword argument.

---

README.md

subprocess.open doesn't exist, use Popen

Correct subprocess example in README
