returntocorp/sgrep

lib/parse_rules.ml
lint-test.py
lint.py
test2/sgrep-v2.yml

Try the rules in https://github.com/returntocorp/sgrep-rules !
No actual changes to sgrep binary itself to report ranges or boolean logic (yet). TBH I'm not sure it will make sense to do so. 
```
ine@mp4~/D/r/sgrep (sgrep-lint-python)> ./lint.py ../sgrep-rules/ ../test-repos/airflow/
running 45 rules from 7 yaml files (0 yaml files were invalid)
{
"results": [
{
"check_id": "sgrep-lint",
"path": "tests/www/test_security.py",
"start": { "line": 78, "col": 9 },
"end": { "line": 78, "col": 13 },
"extra": {
"message":
"sgrep-rules.python.flask.avoid_hardcoded_config_SECRET_KEY: Hardcoded variable `SECRET_KEY` detected. Use environment variables or config files instead",
"line": "NO LINE"
}
},
```

initial sgrep lint in python supporting multiple rules in a directory

---

sgrep.py

When passing single file, os.walk was skipping over the rules in it.
This fixes that.
To test: run `sgrep-lint` with single rule file and see the rule firing and the error/success counter correctly applied.
```
ulziibayarotgonbaatar@ulziibayars-MacBook-Pro sgrep % sgrep-lint ~/Workspace/sgrep-rules/python/flask/secure-static-file-serve.yaml ~/Workspace/sgrep-rules/tests/python/flask/send_static_file/test_send_file_without_path_sanitization.py| jq
running 1 rules from 1 yaml files (0 yaml files were invalid)
{
"matches": [
{
"check_id": "avoid_send_file_without_path_sanitization",
"path": "/Users/ulziibayarotgonbaatar/Workspace/sgrep-rules/tests/python/flask/send_static_file/test_send_file_without_path_sanitization.py",
"start": {
"line": 8,
"col": 10,
"offset": 149
},
"end": {
"line": 8, …
```

Fix single file rule argument

---

bin/main_sgrep.ml

Should fix issue #66
Test plan:
$ ./_build/default/bin/main_sgrep.exe -lang javascript -e foo tests/js/

* bin/main_sgrep.ml: use better Lang.files_of_dirs... when can.

---

sgrep.py
testlint/python/bad.yaml
testlint/run-lint-tests.sh

If evaluation of an expression fails, you will now see:
```
AssertionError: only `pattern-either` or `patterns` expressions can have multiple subpatterns
```
Instead of "invalid index [2]..."
Closes https://github.com/returntocorp/sgrep/issues/91

better handling of invalid keys

---

sgrep.py

New output actually tells you the config name, rule name, and language that the rule failed to parse for:
```
in python/exceptions/exceptions.yaml, pattern in rule raise-not-base-exception can't be parsed for language python: raise ($X: int)
invalidate patterns found inside rules; aborting
```

use validate patterns flag in sgrep

---

bin/main_sgrep.ml
lib/match_result.ml

Test plan:
in bento-core/ repo
git checkout lomalley/sgrep-test
~/sgrep/.../main_sgrep.exe -verbose -rules_file .sgrep.yml bento/
no exn anymore

This should fix issue #106

---

sgrep.py
testlint/python/bad2.yaml

We are incurring a almost 4 second penalty by validating the rules in --config=r2c; in this commit, we add a flag to skip that pattern validation.
We may want to automatically turn this flag on for our golden r2c config.

add a flag to skip pattern validation, which takes 0.05 seconds per rule

---

docs/patterns.md

Just some small edits to normalize capitalization and a few places weren't bolded as intended.

Normalize some formatting / capitalization in docs/patterns.md

---

sgrep.py
testlint/python/bad3.yaml
testlint/run-lint-tests.sh
testlint/test_lint.py

Trying to make the yaml errors less confusing to the end user, closes issue https://github.com/returntocorp/sgrep/issues/210
```
testlint/python/bad.yaml: inside rule 1 (rule id: eqeq-is-bad), pattern fields can't look like this: only ['patterns', 'pattern-either'] operators can have children, but found `and_inside` with children
testlint/python/bad2.yaml has invalid rule key at rule 1 (rule id: eqeq-is-bad), can only have: {'patterns', 'languages', 'id', 'severity', 'pattern', 'message'}
testlint/python/bad3.yaml: inside rule 1 (rule id: test-pattern), pattern fields can't look like this: operand of operator `pattern` ought to have type string, but is <class 'list'>: [{'pattern': '$D = {}'}]
```

clearer error messages for invalid YAML files

---

sgrep.py
testlint/python/bad3.yaml
testlint/run-lint-tests.sh
testlint/test_lint.py

cc @clintgibler
tests in https://github.com/returntocorp/sgrep-rules/pull/185 and https://github.com/returntocorp/sgrep-rules/pull/196
when complete, closes #101 ; see https://github.com/returntocorp/sgrep/pull/166 for prior discussion
Major changes include using proper types and classes for the sgrep output as well as `BooleanRuleExpression` for the formerly-tuple parsed expressions.
Because of the potential for arbitrary code execution, these rules are only run if the command-line flag `--dangerously-allow-arbitrary-code-execution-from-rules` is set

pattern-where-python

---

README.md
bin/main_sgrep.ml
sgrep.py

Closes https://github.com/returntocorp/sgrep/issues/161
Requires https://github.com/returntocorp/pfff/pull/36
And now:
``` 
sgrep --help
-lang                     <str> choose language (valid choices: c, go, golang, java, javascript, js, ml, ocaml, py, python)
...
```

remove python as default language for patterns

---

sgrep_lint/evaluation.py
sgrep_lint/tests/python/bad4.yaml
sgrep_lint/tests/run-lint-tests.sh

Fixes issue with https://sgrep.live/6xY having a bad error message

improve parsing error for invalid types in valid yaml

---

README.md

Added it above the first paragraph as well as in the sgrep description so the word 'sgrep' links to sgrep.live

Added link to sgrep.live

---

.pre-commit-config.yaml
mypy.ini
sgrep_lint/config_resolver.py
sgrep_lint/evaluation.py
sgrep_lint/sgrep_main.py
sgrep_lint/sgrep_types.py
sgrep_lint/test.py
sgrep_lint/util.py
stubs/astpretty.pyi

mypy by default does not run stricter checks. This turns on some
more of the strict mypy options and fixes the codebase to be compliant
with the new stricter settings.

Fix mypy not using strict options

---

sgrep/lib/generic_vs_generic.ml
sgrep/lib/normalize_generic.ml
sgrep/lib/normalize_generic.mli
sgrep/tests/js/equivalence_import_variations.sgrep
sgrep/tests/js/equivalence_import_variations2.js
sgrep/tests/js/equivalence_import_variations2.sgrep
sgrep/tests/js/equivalence_import_variations3.js
sgrep/tests/js/equivalence_import_variations3.sgrep

This fixes the import matching improvements introduced by Drew and Isaac
by doing the flexible matching only if the pattern is simple.
If the pattern is complex, for example searching for the use of
'import *' in Js or Python, it should not match any kind of import.
This fixes issue #197
Test plan:
Many tests included.

Flexible and correct import matching

---

sgrep/lib/generic_vs_generic.ml
sgrep/tests/js/equivalence_varlet.js
sgrep/tests/js/equivalence_varlet.sgrep

This is especially useful for JS (maybe too JS-specific)
Test plan:
test files included

Support 'var' matching also 'let' and 'const'

---

sgrep_lint/sgrep.py
sgrep_lint/sgrep_main.py
sgrep_lint/test.py

Note that this just post-processes the output and I would like to pass this down to the sgrep core to save parsing time etc.
Adding this to here instead of bento because most tools, including grep and flake8, have a way for excluding paths and bento can take advantage of that later to avoid parsing time

Add --exclude to sgrep

---

sgrep_lint/sgrep_main.py

sgrep-lint was printing out information that was not a finding during
the run. Moved to print only when verbose is marked true.

Fix: sgrep-lint printing out number of config files/rules to debug

---

.gitignore
HomebrewFormula/sgrep-r2c.rb

This creates a functional (but pretty janky) brew tap based on the
current state of affairs. Lots more downstream work to knock out:
- Automatically build binaries on tags & add to release
- Fixup the tap to use formulae dependencies instead of copying all
these libs
- fix the linker path to actually look for libraries in the right place
WIP for #371

Create an initial brew tap

---

sgrep_lint/sgrep_main.py

Addresses: https://github.com/returntocorp/enterprise/issues/43. This changes the "errors" in json output to be compatible with https://docs.r2c.dev/en/latest/api/output.html#errors. 
1. make
2. ./build/sgrep.dist/sgrep-lint --json -f ~/Workspace/sgrep-rules/python/django/security/xss-html-email-body.yaml ~/Workspace/rest_xops
3. see the following:
```json
{"results": [], "errors": {"data": [{"check_id": "LexicalError", "path": "/Users/ulziibayarotgonbaatar/Workspace/rest_xops/rest_xops/celery.py", "start": {"line": 32, "col": 35}, "end": {"line": 32, "col": 36}, "extra": {"message": "Lexical error: unrecognized symbol: #", "line": "CELERYD_TASK_TIME_LIMIT = 15 * 60 # \u4efb\u52a1\u8d85\u65f6\u65f6\u95f4"}}, {"check_id": "LexicalError", "path": …
```

Wrap error entries to be compatible with r2c output
